---
abstract: 'Conversion For Ethiopic Numerals in Perl.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Convert-Number-Ethiopic
provides:
  Convert::Number::Ethiopic:
    file: lib/Convert/Number/Ethiopic.pm
    version: '0.21'
requires:
  perl: v5.8.0
resources:
  bugtracker: https://github.com/dyacob/Convert-Number-Ethiopic/issues
  homepage: https://github.com/dyacob/Convert-Number-Ethiopic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/Convert-Number-Ethiopic.git
version: '0.21'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
